# Generated by Django 6.0.2 on 2026-02-09 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("human_status", models.CharField(max_length=100)),
                ("water_status", models.CharField(max_length=100)),
                ("temperature", models.CharField(max_length=100)),
                ("moisture_status", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
